[directory]
style = "blue"
truncate_to_repo = false
truncation_symbol = "…/"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[cmd_duration]
disabled = true

[aws]
format = 'on [$symbol$profile]($style)'
